### PR TITLE
add windows support (fix #2)

### LINKED ISSUE #2: Implement windows support
Using [performance counters](https://msdn.microsoft.com/en-us/library/windows/desktop/aa373083%28v=vs.85%29.aspx). PR welcome.

### PR DESCRIPTION
**Pull request by tatchi**
This upstream changes from https://github.com/fdopen/opam-repository-mingw/commit/4c6537c0138f493ddf705057cb917eecf77e64f1 to add windows support.

Should fix #2

### CODE REVIEW

**Comment by dbuenzli** [comment]
Thanks will integrate that asap ! Just to make sure, @fdopen are you ok we integrate your patch [under this license](https://github.com/dbuenzli/mtime/blob/master/LICENSE.md)..

**Comment by fdopen** [comment]
yes, i'm ok with it.

**Comment by tatchi** [comment]
Hey, anything preventing that one from being merged?

**Comment by dbuenzli** [comment]
The fact that I forgot maybe 😬. Sorry will do that in the upcoming days.

**Comment by dbuenzli** [comment]
Thanks all the patch is in as d404f5a70c88eb3ce43

**Comment by dbuenzli** [comment]
Release https://github.com/ocaml/opam-repository/pull/19821

**Pull request closed without merging**
